import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {CLUBS,fromFotmob,fromEspn,from365,mergeSchedules,fotmobGoals,espnGoals,scores365Goals,fotmobTable,espnTable,scores365Table,rssNews,fmLogo} from './providers.mjs';
import {selectMatches} from '../dist/logic.js';
const root=path.resolve(import.meta.dirname,'..');
const output=process.env.OUTPUT_JSON?path.resolve(process.env.OUTPUT_JSON):path.join(root,'dist/data/football.json');
const at=new Date().toISOString();
const failures=[],checks=[];
const blocked=new Set((process.env.DISABLE_PROVIDERS||'').split(','));
const memo=new Map();
async function request(url,provider,text=false){if(blocked.has(provider))throw Error(`${provider} intentionally disabled`);if(memo.has(url))return memo.get(url);const p=(async()=>{let last;for(let i=0;i<2;i++){try{const r=await fetch(url,{headers:{'User-Agent':'JarvisFootball/1.0 (public football schedule collector)','Accept':text?'application/rss+xml, text/xml':'application/json'},signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error(`${r.status} ${new URL(url).hostname}`);const data=await r[text?'text':'json']();checks.push({provider,url,at,status:'ok'});return data}catch(e){last=e}}throw last})();memo.set(url,p);return p}
async function safe(label,fn){try{return await fn()}catch(e){failures.push({label,error:e.message});return null}}
const fotmob=(part)=>request(`https://www.fotmob.com/api/data/${part}`,'FotMob');
const espn=(part)=>request(`https://site.api.espn.com/apis/site/v2/sports/soccer/${part}`,'ESPN');
const scores=(part)=>request(`https://webws.365scores.com/web/${part}${part.includes('?')?'&':'?'}appTypeId=5&langId=1&timezoneName=Asia%2FSeoul`,'365Scores');
let previous;try{previous=JSON.parse(await fs.readFile(output,'utf8'))}catch{}
async function loadAlternative(club){if(club.espn){const [next,last,table]=await Promise.all([safe(`${club.key}:ESPN fixtures`,()=>espn(`all/teams/${club.espn}/schedule?fixture=true`)),safe(`${club.key}:ESPN results`,()=>espn(`all/teams/${club.espn}/schedule`)),safe(`${club.key}:ESPN table`,()=>request(`https://site.web.api.espn.com/apis/v2/sports/soccer/${club.espnLeague}/standings`,'ESPN'))]);return {matches:[...(next?.events||[]),...(last?.events||[])].map(m=>fromEspn(m,at)),table:table&&espnTable(table,at)}}
const [next,last]=await Promise.all([safe('incheon:365 fixtures',()=>scores(`games/fixtures/?competitors=${club.scores365}`)),safe('incheon:365 results',()=>scores(`games/results/?competitors=${club.scores365}`))]);const identity=[...(next?.competitors||[]),...(last?.competitors||[])].find(x=>x.id===club.scores365);const league=identity?.mainCompetitionId;const table=league?await safe('incheon:365 table',()=>scores(`standings/?competitions=${league}`)):null;return {matches:[...(next?.games||[]),...(last?.games||[])].map(m=>from365(m,at)),table:table&&scores365Table(table,at)}}
async function detail(m,provider=m.provider,id=m.providerId,league=m.competitionId){if(provider==='FotMob'){const j=await fotmob(`matchDetails?matchId=${id}`);return fotmobGoals(j)}if(provider==='ESPN'){const j=await espn(`${league||'all'}/summary?event=${id}`);return espnGoals(j)}return scores365Goals(await scores(`game/?gameId=${id}`))}
async function collectClub(club){const old=previous?.teams?.find(t=>t.key===club.key);const [primary,alternative,news]=await Promise.all([safe(`${club.key}:FotMob`,()=>fotmob(`teams?id=${club.id}`)),loadAlternative(club),safe(`${club.key}:news`,async()=>{const xml=await request(`https://news.google.com/rss/search?q=${encodeURIComponent(club.query+' when:14d')}&hl=ko&gl=KR&ceid=KR:ko`,'Google News',true);const items=rssNews(xml);if(!items.length)throw Error('No news in feed');return items})]);
let matches=mergeSchedules((primary?.fixtures?.allFixtures?.fixtures||[]).map(m=>fromFotmob(m,at)),alternative.matches);let stale=false;if(!matches.length){matches=old?.matches||[];stale=true}
// Keep a useful rolling buffer for page loads between automatic runs.
const visible=selectMatches(matches);const next=matches.filter(m=>['scheduled','live'].includes(m.status)&&Date.parse(m.date)>Date.now()-3*3600000).slice(0,12);const last=matches.filter(m=>m.status==='finished').slice(-4);matches=[...last,...next];
await Promise.all(visible.recent.map(async m=>{let goals=await safe(`${club.key}:${m.id}:goals`,()=>detail(m));const expected=m.home.score+m.away.score;const complete=g=>Array.isArray(g)&&g.length===expected&&g.every(x=>x.player&&x.minute);if(!complete(goals)&&m.alternative){const g=await safe(`${club.key}:${m.id}:backup goals`,()=>detail(m,m.alternative.provider,m.alternative.id,m.alternative.competitionId));if(complete(g))goals=g;}if(!complete(goals)){const cached=old?.matches?.find(x=>x.id===m.id&&x.home.score===m.home.score&&x.away.score===m.away.score);if(cached?.goalsStatus==='complete')goals=cached.goals;}m.goals=goals||[];m.goalsStatus=complete(goals)?'complete':'pending';if(!complete(goals))failures.push({label:`${club.key}:${m.id}:goal completeness`,error:`Expected ${expected}, received ${m.goals.length}`})}));
let standings=primary&&fotmobTable(primary,club,at);if(!standings?.rows.length)standings=alternative.table;if(!standings?.rows.length&&old?.standings)standings={...old.standings,stale:true};const source=primary?'FotMob':alternative.matches.length?(club.espn?'ESPN':'365Scores'):old?.source||'unavailable';
return {...club,logo:primary?fmLogo(club.id):(matches.find(m=>m.home.id===club.id)?.home.logo||matches.find(m=>m.away.id===club.id)?.away.logo||old?.logo||fmLogo(club.id)),league:standings?.league||old?.league||'',source,fetchedAt:stale?old?.fetchedAt:at,stale,matches,standings,news:news||old?.news||[],newsFetchedAt:news?at:old?.newsFetchedAt,newsStale:!news};}
const teams=[];for(const club of CLUBS){teams.push(await collectClub(club));console.log(`Collected ${club.key}: ${teams.at(-1).matches.length} matches, ${teams.at(-1).standings?.rows.length||0} table rows, ${teams.at(-1).news.length} news`)}
// Cache verified real crests on the same origin to avoid client hotlink failures.
const logos=new Map();for(const t of teams){for(const o of [t,...t.matches.flatMap(m=>[m.home,m.away]),...(t.standings?.rows||[])]){if(!o.logo)continue;if(!logos.has(o.logo))logos.set(o.logo,[]);logos.get(o.logo).push(o)}}
await fs.mkdir(path.join(root,'dist/assets/crests'),{recursive:true});
if(!process.env.SKIP_LOGOS){const entries=[...logos];for(let i=0;i<entries.length;i+=8)await Promise.all(entries.slice(i,i+8).map(async([url,objects])=>{if(url.startsWith('./assets/'))return;try{const name=crypto.createHash('sha256').update(url).digest('hex').slice(0,16)+'.png';const dest=path.join(root,'dist/assets/crests',name);try{await fs.access(dest)}catch{const r=await fetch(url,{signal:AbortSignal.timeout(18000)});if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw Error(`crest ${r.status}`);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length<200)throw Error('Empty crest');await fs.writeFile(dest,bytes)}for(const o of objects){o.logoOriginal=url;o.logo=`./assets/crests/${name}`}}catch(e){failures.push({label:'crest '+url,error:e.message})}}))}
const health=teams.map(t=>{const s=selectMatches(t.matches);return {team:t.key,upcoming:s.upcoming.length,recent:s.recent.length,goalDetails:s.recent.filter(m=>m.goalsStatus==='complete').length,confirmedTimes:s.upcoming.filter(m=>m.timeStatus==='confirmed').length,crossChecked:s.upcoming.concat(s.recent).filter(m=>m.crossChecked).length,standings:t.standings?.rows.length||0,news:t.news.length,stale:t.stale}});
const valid=health.every(h=>h.upcoming>=3&&h.recent>=2&&h.goalDetails===2&&h.standings>=10&&h.news>0&&!h.stale);
const result={schemaVersion:1,generatedAt:at,refreshMinutes:30,timezone:'Asia/Seoul',health,failures,teams};
await fs.mkdir(path.dirname(output),{recursive:true});await fs.writeFile(output+'.tmp',JSON.stringify(result,null,2)+'\n');await fs.rename(output+'.tmp',output);
await fs.mkdir(path.join(root,'work'),{recursive:true});await fs.writeFile(path.join(root,'work/collection-report.json'),JSON.stringify({at,valid,health,failures,checks},null,2));
console.log(JSON.stringify({valid,health,failures},null,2));
if(process.env.STRICT_DATA==='1'&&!valid)process.exitCode=1;
