// Public read-only feeds. No credentials are sent to data providers.
export const CLUBS=[
 {key:'united',id:'10260',name:'맨체스터 유나이티드',query:'맨체스터 유나이티드',espn:'360',espnLeague:'eng.1',leagueId:47},
 {key:'spurs',id:'8586',name:'토트넘 홋스퍼',query:'토트넘',espn:'367',espnLeague:'eng.1',leagueId:47},
 {key:'atleti',id:'9906',name:'아틀레티코 마드리드',query:'아틀레티코 마드리드',espn:'1068',espnLeague:'esp.1',leagueId:87},
 {key:'real',id:'8633',name:'레알 마드리드',query:'레알 마드리드',espn:'86',espnLeague:'esp.1',leagueId:87},
 {key:'incheon',id:'133895',name:'인천 유나이티드',query:'인천 유나이티드',scores365:9819}
];
const groups=[
 ['맨체스터 유나이티드','Man United','Manchester United'],['토트넘 홋스퍼','Tottenham','Tottenham Hotspur'],['아틀레티코 마드리드','Atletico Madrid','Atlético Madrid','Atletico de Madrid'],['레알 마드리드','Real Madrid'],['인천 유나이티드','Incheon United','Incheon United FC'],
 ['맨체스터 시티','Manchester City','Man City'],['아스널','Arsenal'],['리버풀','Liverpool'],['첼시','Chelsea'],['브라이턴','Brighton','Brighton & Hove Albion'],['풀럼','Fulham'],['애스턴 빌라','Aston Villa'],['크리스털 팰리스','Crystal Palace'],['뉴캐슬','Newcastle','Newcastle United'],['브렌트퍼드','Brentford'],['리즈 유나이티드','Leeds','Leeds United'],['노팅엄 포리스트','Nottingham Forest','Nottm Forest'],['본머스','Bournemouth','AFC Bournemouth'],['선덜랜드','Sunderland'],['코번트리 시티','Coventry City','Coventry'],['에버턴','Everton'],['입스위치 타운','Ipswich Town','Ipswich'],['웨스트햄','West Ham','West Ham United'],['울버햄프턴','Wolves','Wolverhampton Wanderers'],['번리','Burnley'],['레스터 시티','Leicester City'],['사우샘프턴','Southampton'],
 ['바르셀로나','Barcelona','FC Barcelona'],['레알 베티스','Real Betis','Betis'],['비야레알','Villarreal'],['발렌시아','Valencia'],['세비야','Sevilla'],['아틀레틱 클루브','Athletic Club','Athletic Bilbao'],['레알 소시에다드','Real Sociedad'],['오사수나','Osasuna'],['헤타페','Getafe'],['알라베스','Deportivo Alaves','Deportivo Alavés','Alaves'],['셀타 비고','Celta Vigo','Celta de Vigo'],['에스파뇰','Espanyol'],['라요 바예카노','Rayo Vallecano'],['마요르카','Mallorca'],['지로나','Girona'],['엘체','Elche'],['레반테','Levante'],['레알 오비에도','Real Oviedo'],['라스팔마스','Las Palmas'],['알메리아','Almeria','Almería'],['라싱 산탄데르','Racing Santander'],['데포르티보','Deportivo La Coruna','Deportivo La Coruña'],
 ['FC 서울','FC Seoul'],['울산 HD','Ulsan HD','Ulsan HD FC','Ulsan Hyundai'],['대전 하나 시티즌','Daejeon Hana Citizen','Daejeon Citizen'],['전북 현대','Jeonbuk Hyundai Motors','Jeonbuk Hyundai Motors FC','Jeonbuk Motors'],['강원 FC','Gangwon FC','Gangwon'],['포항 스틸러스','Pohang Steelers'],['제주 SK','Jeju SK','Jeju United'],['김천 상무','Gimcheon Sangmu','Gimcheon Sangmu FC'],['광주 FC','Gwangju FC','Gwangju'],['FC 안양','FC Anyang'],['부천 FC 1995','Bucheon FC 1995'],['대구 FC','Daegu FC'],['수원 삼성','Suwon Samsung Bluewings'],['수원 FC','Suwon FC']
];
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9가-힣]/g,'');
const names=new Map(groups.flatMap(g=>g.map(n=>[normalize(n),g[0]])));
export const localName=n=>names.get(normalize(n))||n;
export const leagueName=n=>({'Premier League':'프리미어리그','English Premier League':'프리미어리그','LaLiga':'라리가','LaLiga EA Sports':'라리가','Spanish LALIGA':'라리가','La Liga':'라리가','K-League 1':'K리그 1','K League 1':'K리그 1','K-League 2':'K리그 2','K League 2':'K리그 2','EFL Cup':'카라바오컵','English Carabao Cup':'카라바오컵','Champions League':'UEFA 챔피언스리그','UEFA Champions League':'UEFA 챔피언스리그','Europa League':'UEFA 유로파리그','UEFA Europa League':'UEFA 유로파리그','FA Cup':'FA컵','Copa del Rey':'코파 델 레이'})[n]||n;
export const fmLogo=id=>`https://images.fotmob.com/image_resources/logo/teamlogo/${id}.png`;
export function canonicalTeam(t,provider){const name=localName(t.name||t.displayName);const known=CLUBS.find(c=>c.name===name);const id=known?.id||(provider==='FotMob'?String(t.id):`${provider==='ESPN'?'e':'s'}${t.id}`);return {id,name,originalName:t.name||t.displayName,logo:provider==='FotMob'?fmLogo(t.id):provider==='ESPN'?(t.logos?.[0]?.href||t.logo):`https://imagecache.365scores.com/image/upload/f_png,w_128,h_128,c_limit,q_auto:eco/v${t.imageVersion||1}/Competitors/${t.id}`}}
export function timeState(status={},date){const text=JSON.stringify(status.reason||{})+' '+(status.statusText||'');if(status.timeValid===false||status.isTimeToBeAnnounced||status.timeToBeConfirmed||status.timeTBD||status.isDateTimeTBD||/to be (?:confirmed|announced)|\bTBD\b|\bTBA\b/i.test(text))return 'pending';return date&&Number.isFinite(Date.parse(date))?'confirmed':'unknown'}
export function fromFotmob(m,at){const s=m.status||{},date=s.utcTime,finished=s.finished===true;return {id:`f${m.id}`,providerId:String(m.id),provider:'FotMob',date,kickoff:date,timeStatus:timeState(s,date),status:s.cancelled?'cancelled':s.reason?.short==='Postponed'?'postponed':finished?'finished':s.started?'live':'scheduled',competition:leagueName(m.tournament.name),competitionId:String(m.tournament.leagueId),home:{...canonicalTeam(m.home,'FotMob'),score:finished||s.started?m.home.score:null},away:{...canonicalTeam(m.away,'FotMob'),score:finished||s.started?m.away.score:null},source:'FotMob',sourceUrl:`https://www.fotmob.com${m.pageUrl}`,fetchedAt:at,goals:[],goalsStatus:finished?'pending':'not-applicable'}}
export function fromEspn(m,at){const c=m.competitions[0],s=c.status?.type||{},home=c.competitors.find(t=>t.homeAway==='home'),away=c.competitors.find(t=>t.homeAway==='away');const member=t=>({...canonicalTeam(t.team,'ESPN'),score:s.completed||s.state==='in'?Number(t.score?.value??t.score):null});return {id:`e${m.id}`,providerId:m.id,provider:'ESPN',date:m.date,kickoff:m.date,timeStatus:timeState({timeValid:m.timeValid??c.timeValid,...s},m.date),status:s.completed?'finished':s.state==='in'?'live':/postpon/i.test(s.name)?'postponed':/cancel/i.test(s.name)?'cancelled':'scheduled',competition:leagueName(m.league?.name||m.seasonType?.name),competitionId:m.league?.slug,home:member(home),away:member(away),neutral:c.neutralSite,source:'ESPN',sourceUrl:m.links?.find(l=>l.rel?.includes('summary'))?.href||`https://www.espn.com/soccer/match/_/gameId/${m.id}`,fetchedAt:at,goals:[],goalsStatus:s.completed?'pending':'not-applicable'}}
export function from365(m,at){const finished=m.statusGroup===4;const member=t=>({...canonicalTeam(t,'365Scores'),score:finished||m.statusGroup===3?t.score:null});return {id:`s${m.id}`,providerId:String(m.id),provider:'365Scores',date:m.startTime,kickoff:m.startTime,timeStatus:timeState(m,m.startTime),status:finished?'finished':m.statusGroup===3?'live':/postpon/i.test(m.statusText)?'postponed':/cancel/i.test(m.statusText)?'cancelled':'scheduled',competition:leagueName(m.competitionDisplayName),competitionId:String(m.competitionId),home:member(m.homeCompetitor),away:member(m.awayCompetitor),source:'365Scores',sourceUrl:`https://www.365scores.com/football/match/${m.homeCompetitor.nameForURL}-${m.awayCompetitor.nameForURL}-${m.homeCompetitor.id}-${m.awayCompetitor.id}-${m.id}`,fetchedAt:at,goals:[],goalsStatus:finished?'pending':'not-applicable'}}
export function sameMatch(a,b){return localName(a.home.originalName||a.home.name)===localName(b.home.originalName||b.home.name)&&localName(a.away.originalName||a.away.name)===localName(b.away.originalName||b.away.name)&&Math.abs(Date.parse(a.date)-Date.parse(b.date))<48*3600000}
export function mergeSchedules(primary,backup){const result=primary.map(m=>({...m,home:{...m.home},away:{...m.away}}));for(const b of backup){const a=result.find(m=>sameMatch(m,b));if(!a){result.push(b);continue}a.alternative={provider:b.provider,id:b.providerId,competitionId:b.competitionId,url:b.sourceUrl};a.crossChecked=true;if(a.timeStatus!=='confirmed'&&b.timeStatus==='confirmed'){a.kickoff=b.kickoff;a.date=b.date;a.timeStatus='confirmed';a.timeSource=b.source;}else if(a.timeStatus==='confirmed'&&b.timeStatus==='confirmed'&&Date.parse(a.kickoff)!==Date.parse(b.kickoff)){a.timeConflict=true}if(a.status==='finished'&&b.status==='finished'&&(a.home.score!==b.home.score||a.away.score!==b.away.score)){a.scoreConflict=true}}
return result.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))}
export function fotmobGoals(j){const events=j.content?.matchFacts?.events?.events??[...Object.values(j.header?.events?.homeTeamGoals||{}).flat(),...Object.values(j.header?.events?.awayTeamGoals||{}).flat()];return events.filter(e=>e.type==='Goal'&&!e.isPenaltyShootoutEvent).map(e=>({minute:String(e.timeStr??`${e.time}${e.overloadTime?'+'+e.overloadTime:''}`).replace(/\s/g,''),player:e.player?.name||e.nameStr,side:e.isHome?'home':'away',penalty:/penalty/i.test(`${e.goalDescription||''} ${e.goalDescriptionKey||''}`)||e.shotmapEvent?.situation==='Penalty',ownGoal:!!e.ownGoal,assist:e.assistInput||null}));}
export function espnGoals(j){const c=j.header?.competitions?.[0];return (c?.details||[]).filter(e=>e.scoringPlay).map(e=>{const comment=j.commentary?.find(x=>x.play?.scoringPlay&&x.play.clock?.displayValue===e.clock.displayValue);return {minute:e.clock.displayValue.replace(/['′]/g,''),player:e.participants?.[0]?.athlete?.displayName,side:e.team.id===c.competitors.find(t=>t.homeAway==='home').id?'home':'away',penalty:!!e.penaltyKick,ownGoal:!!e.ownGoal,assist:comment?.text?.match(/Assisted by (.+?)(?: with| following|\.)/)?.[1]||null}})}
export function scores365Goals(j){const g=j.game;const player=id=>g.members?.find(m=>m.id===id)?.name;return (g.events||[]).filter(e=>e.eventType?.name==='Goal').map(e=>({minute:(e.gameTimeDisplay||`${e.gameTime}${e.addedTime?'+'+e.addedTime:''}`).replace(/['′]/g,''),player:player(e.playerId),side:e.competitorId===g.homeCompetitor.id?'home':'away',penalty:/penalty/i.test(e.eventType.subTypeName),ownGoal:/own/i.test(e.eventType.subTypeName),assist:player(e.extraPlayers?.[0])||null}))}
export function fotmobTable(j,club,at){const candidates=(j.table||[]).map(x=>x.data).filter(Boolean);const s=candidates.find(x=>x.table?.all?.some(r=>String(r.id)===club.id)&&(!club.leagueId||x.leagueId===club.leagueId));if(!s)return null;return {league:leagueName(s.leagueName),leagueId:String(s.leagueId),season:String(j.details.latestSeason||j.overview?.season||''),fetchedAt:at,source:'FotMob',sourceUrl:`https://www.fotmob.com${s.pageUrl}`,rows:s.table.all.map(r=>({...canonicalTeam(r,'FotMob'),rank:r.idx,played:r.played,wins:r.wins,draws:r.draws,losses:r.losses,gd:r.goalConDiff,points:r.pts}))}}
export function espnTable(j,at){const groups=j.children||[];const s=groups.find(x=>x.standings?.entries?.length)?.standings;if(!s)return null;return {league:leagueName(j.name),season:j.season?.displayName||String(j.season?.year||''),fetchedAt:at,source:'ESPN',sourceUrl:`https://www.espn.com/soccer/standings/_/league/${j.abbreviation==='Premier League'?'eng.1':'esp.1'}`,rows:s.entries.map(r=>{const v=n=>r.stats.find(x=>x.name===n)?.value;return {...canonicalTeam(r.team,'ESPN'),rank:v('rank'),played:v('gamesPlayed'),wins:v('wins'),draws:v('ties'),losses:v('losses'),gd:v('pointDifferential'),points:v('points')}})}}
export function scores365Table(j,at){const s=j.standings?.find(x=>x.isCurrentStage)||j.standings?.[0];if(!s?.rows?.length)return null;return {league:leagueName(s.displayName),season:String(new Date(at).getUTCFullYear()),fetchedAt:at,source:'365Scores',sourceUrl:`https://www.365scores.com/football/league/${s.competitionId}/standings`,rows:s.rows.map(r=>({...canonicalTeam(r.competitor,'365Scores'),rank:r.position,played:r.gamePlayed,wins:r.gamesWon,draws:r.gamesEven,losses:r.gamesLost,gd:r.ratio,points:r.points}))}}
const decode=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;|&#39;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/<[^>]*>/g,'');
export function rssNews(xml){return [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(([,s])=>{const tag=k=>decode(s.match(new RegExp(`<${k}(?: [^>]*)?>([\\s\\S]*?)</${k}>`))?.[1]);const source=tag('source');return {title:tag('title').replace(new RegExp(' - '+source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$'),''),source:source||'뉴스',publishedAt:tag('pubDate'),url:tag('link')}}).filter(n=>n.title&&/^https?:\/\//.test(n.url)&&Number.isFinite(Date.parse(n.publishedAt))).map(n=>({...n,publishedAt:new Date(n.publishedAt).toISOString()})).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,8)}
